---
language: ruby
before_install:
  - gem install bundler
install: bundle _${BUNDLER_VERSION}_ install
script: bundle _${BUNDLER_VERSION}_ exec rspec --color --format documentation
notifications:
  email: true
rvm:
  - 2.0.0
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
